### ISSUE TITLE
Make testable

### ISSUE THREAD

**Issue by Lewiscowles1986** [koenrh/delete-tweets#11]
I know it works as we've both tested by running, but it'd be great to have something so we can run a unit-test suite, perhaps even a test against twitter using https://github.com/brightcove/brine or similar?

**Comment by koenrh** [comment]
Agreed.

Added some basic tests in https://github.com/koenrh/delete-tweets/pull/17 (using pytest).

**Comment by Lewiscowles1986** [comment]
Thank you!
