### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by fleizean** [koenrh/delete-tweets#116]
Hey boys i wondered how to solve this error: Exception: [{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}]

Do I have to pay for Basic mode?

<img width="1047" alt="Ekran Resmi 2023-05-07 17 21 23" src="https://user-images.githubusercontent.com/66090171/236683258-ebbe2eaf-5372-4784-8eeb-fc931a3e213e.png">

**Comment by borabafli** [comment]
I have the same problem
