### ISSUE TITLE
No more tweets.csv file

### ISSUE THREAD

**Issue by justdvl** [koenrh/delete-tweets#16]
Trying to make this work, but Twitter didn't provide the tweets.csv file. Did they change the export structure?
They only provide .js files, one of them tweet.js, where all the tweets are.
Hovewer this seems to have different json structure, as I am getting error:

```
  File "deletetweets.py", line 20, in delete
    tweet_id = int(row["tweet_id"])
KeyError: 'tweet_id'
```

Perhaps correction will be necessary (in which case I can do it).

**Comment by koenrh** [comment]
Did you follow the instructions in the [README](https://github.com/koenrh/delete-tweets#get-your-tweet-archive)?

Confusingly, there are now two ways to export your data from Twitter (see my comment here: https://github.com/koenrh/delete-tweets/pull/5#issuecomment-408890053).

**Comment by ulissesalmeida** [comment]
I followed the README instructions, I think Twitter removed any reference to the `twitter.csv` file.
