### ISSUE TITLE
ImportError: No module named backports

### ISSUE THREAD

**Issue by siemvaessen** [koenrh/delete-tweets#18]
Hi,

Followed the Readme but getting an ImportError: No module named backports. 

Running a Macbook - not sure how to solve this. Any pointers?

**Comment by siemvaessen** [comment]
Right, I get this upon checking requirements: 

Could not find a version that satisfies the requirement backports (from versions: ) .. Mhmm

**Comment by siemvaessen** [comment]
Right, for some reason just running 'pip install backports.csv' solved my issue.

**Comment by koenrh** [comment]
Ah, I see, that one should be added to the requirements.txt file. I'll fix that.

Thanks for reporting!

**Comment by koenrh** [comment]
@miguelssrs Thanks for reporting (and clarifying that it indeed works with Python 3)! I'll try to fix it this week and/or make it clear how to work around it in the README.

**Comment by koenrh** [comment]
Fixed in https://github.com/koenrh/delete-tweets/pull/25 by only requiring the 'backports' version for Python version < 3.
