### ISSUE TITLE
ImportError: No module named twitter

### ISSUE THREAD

**Issue by selflessmind** [koenrh/delete-tweets#19]
Everything seemed to go ok until I tried to delete tweets and got the following error message:

> File "deletetweets.py", line 8, in <module>
>     import twitter
> ImportError: No module named twitter

**Comment by koenrh** [comment]
Did you install the dependencies using `pip install -r requirements.txt` ?

**Comment by selflessmind** [comment]
> Did you install the dependencies using `pip install -r requirements.txt` ?

I did and there were no errors, I even tried updating to twitter 3.5 but had the same error message.

**Comment by selflessmind** [comment]
that command gives the following:

> MacBook-Pro:delete-tweets mercury$ pip list | grep twitter
> python-twitter    3.4.2

**Comment by Botros84** [comment]
orwell84@laptop:~/delete-tweets$ pip list | grep twitter
python-twitter    3.5

but still getting this error

Traceback (most recent call last):
  File "deletetweets.py", line 9, in <module>
    import twitter
ImportError: No module named twitter

**Comment by koenrh** [comment]
It is kind of hard to debug these errors remotely without knowing how your Python environments are setup.

However, what you could do is running scripts such as these in a virtual Python environment:

1. Install [Virtualenv](https://virtualenv.pypa.io/en/latest/): `pip install virtualenv`.
1. Go to the directory where you checked out this repository.
1. Create a new virtual environment by running `virtualenv venv`.
1. Activate the environment: `source venv/bin/activate`.
1. Install the dependencies: `pip install -r requirements.txt`.
1.  Then you should be able to run `python deletetweets.py ...`.

**Comment by codawithacurse** [comment]
I I also got the "ImportError: No module named twitter" error. I did install the dependencies but when I typed "pip install -r requirements.txt" I got the error "-bash: pip: command not found", however it worked with I used pip3 instead of pip. 

When I did that, it appeared to work but I did get a message that said "Ignoring backports.csv: markers 'python_version < "3.0" don't match your environment".

I'm new with this stuff so I would appreciate any direction. I originally installed python on my mac via this guide: http://installpython.com/

**Comment by koenrh** [comment]
>When I did that, it appeared to work but I did get a message that said "Ignoring backports.csv: markers 'python_version < "3.0" don't match your environment".

You can ignore this. It is only informational. It tells you that you are using Python 3 and thus do not need the "backports" dependency (only needed when you are using the Python 2).

**Comment by codawithacurse** [comment]
Thanks, but what about the import twitter module error?

**Comment by koenrh** [comment]
@codawithacurse Apologies for the delay. Are you running the script using the `python` executable? If so, what version of Python is it? (see `python -V`)

**Comment by codawithacurse** [comment]
@koenrh no worries - when I run that it shows "Python 2.7.10".

**Comment by codawithacurse** [comment]
I was able to get it to work using the venv method you suggested, but I had to run the command with a file argument at the end, like this: 

python deletetweets.py -d 2013-10-01 tweets.csv
