### ISSUE TITLE
About variables

### ISSUE THREAD

**Issue by spouyllau** [koenrh/delete-tweets#20]
It's not clear for me, where paste : 

TWITTER_CONSUMER_KEY="[your consumer key]"
TWITTER_CONSUMER_SECRET="[your consumer secret]"
TWITTER_ACCESS_TOKEN="[your access token]"
TWITTER_ACCESS_TOKEN_SECRET="[your access token secret]"

Best,

S.

**Comment by TheAuracle** [comment]
I too am having the same issue. Bit of a newb using Python so I'm not sure how one sets the os.environ variables.

For example, when I replace _'TWITTER_CONSUMER_KEY'_ in line 61 **(consumer_key=os.environ['TWITTER_CONSUMER_KEY']**, the error message printed is _No consumer key/secret and/or access token/secret set._

**Comment by koenrh** [comment]
You need set these four variables as _environment variables_.

Assuming you are using Bash as your default shell, you need to use the `export` command to export these variables to your current environment:

```bash
export TWITTER_CONSUMER_KEY="foo"
export TWITTER_CONSUMER_SECRET="bar"
export TWITTER_ACCESS_TOKEN="baz"
export TWITTER_ACCESS_TOKEN_SECRET="foobar"
```

Then you could quickly verify that these environment variables are set by using `env` and `grep`:

```bash
$ env | grep TWITTER
TWITTER_CONSUMER_KEY=foo
TWITTER_CONSUMER_SECRET=bar
TWITTER_ACCESS_TOKEN=baz
TWITTER_ACCESS_TOKEN_SECRET=foobar
```

This is not clear from the README, I'll fix that.

Let me know if this works (or not).

**Comment by TheAuracle** [comment]
Giving this a try now. Thank you for your prompt response! I'll be in touch. 😄

**Comment by TheAuracle** [comment]
Good news everyone! That export command did the trick! Everything is running as it should! Thank you so much for the clarification!

Also, should mention that I used Git Bash for Windows to do everything as previously instructed.

**Comment by koenrh** [comment]
Cool!

I have updated the README in https://github.com/koenrh/delete-tweets/pull/21.
