### ISSUE TITLE
Twitter API credentials not set.

### ISSUE THREAD

**Issue by jaybird34** [koenrh/delete-tweets#27]
Hi koenrh,

Running from a command line (not BASH), I keep getting "Twitter API credentials not set." even though I've set them where specified in two places. I'm not sure if it's something I'm doing or if others are experiencing similar. Thank you.

**Comment by koenrh** [comment]
Did you export the variables to your environment as described in [this section](https://github.com/koenrh/delete-tweets#configure-your-environment)?

That is (note the `export` command):

```bash
export TWITTER_CONSUMER_KEY="[your consumer key]"
export TWITTER_CONSUMER_SECRET="[your consumer secret]"
export TWITTER_ACCESS_TOKEN="[your access token]"
export TWITTER_ACCESS_TOKEN_SECRET="[your access token secret]"
```

**Comment by jaybird34** [comment]
Forgive my ignorance... I've never used the export command. My confusion is where to run that script? Can I put it in the deletetweets.py file?


JL
Sent from my iPhone

On Jan 2, 2019, at 5:12 AM, Koen Rouwhorst <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you export the variables to your environment as described in this section<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkoenrh%2Fdelete-tweets%23configure-your-environment&data=02%7C01%7C%7C3d65758503cc4cc33b2208d670ab88a6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636820279359572738&sdata=mYVXQW5y9LNIbMmtlMokc2Ma2NaED%2F0Nm7ZHZ3o%2BcMU%3D&reserved=0>?

That is (note the export command):

export TWITTER_CONSUMER_KEY="[your consumer key]"
export TWITTER_CONSUMER_SECRET="[your consumer secret]"
export TWITTER_ACCESS_TOKEN="[your access token]"
export TWITTER_ACCESS_TOKEN_SECRET="[your access token secret]"

**Comment by koenrh** [comment]
No worries.

No, the `export` command is Bash (which is a particular shell) built-in command. You need to run that command in your shell, which usually is Bash. You access that shell in a terminal app (e.g. Terminal.app on Mac, Command Prompt/cmd.exe on Windows).

What OS are you running? Windows?

**Comment by jaybird34** [comment]
I see. I'm running Windows 10. I'm actually pretty experienced in python, however I'm typically doing predictive modeling and have less exposure to other areas, this being one of them. My only experience with bash is with python anywhere just basic stuff.

Do I just type out "export(stuff goes here)" in the command line from cmd.exe?

I really appreciate your help. I'm sure it's kind of annoying haha.


JL
Sent from my iPhone

On Jan 2, 2019, at 9:49 AM, Koen Rouwhorst <notifications@github.com<mailto:notifications@github.com>> wrote:


No worries.

No, the export command is Bash (which is a particular shell) built-in command. You need to run that command in your shell, which usually is Bash. You access that shell in a terminal app (e.g. Terminal.app on Mac, Command Prompt/cmd.exe on Windows).

What OS are you running? Windows?

**Comment by koenrh** [comment]
>Do I just type out "export(stuff goes here)" in the command line from cmd.exe?

No, the syntax is a little different. I'm not that familiar with the Windows 'Command Prompt', but as far as I understand you could set the environment variables as follows (no quotes or brackets):

```batchfile
set TWITTER_CONSUMER_KEY=[your consumer key]
set TWITTER_CONSUMER_SECRET=[your consumer secret]
set TWITTER_ACCESS_TOKEN=[your access token]
set TWITTER_ACCESS_TOKEN_SECRET=[your access token secret]
```

After which you could probably run the script using the Python executable:

```batchfile
python.exe deletetweets.py ...
```

Let me know if that works. I'll update the README to add instructions for Windows users.

**Comment by jaybird34** [comment]
Thank you so much. I will give this a try tonight or in the morning and report back. I appreciate your time with this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jaybird34** [comment]
I tried using “set” for each of the twitter keys from the command line and no luck. Still says Twitter API credentials not set.

[cid:image003.png@01D4A364.37290800]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by koenrh** [comment]
I'll see if I can get my hands on a Windows (virtual) machine to test it myself.

Did you attach an image? (I don't see it show up on GitHub)

**Comment by koenrh** [comment]
Please reopen if needed.

**Comment by viktae** [comment]
Hello,
I'm using Bash (on Windows with the Linux subsystem), everything should be working but I get the same error. I checked my ENV variables and all of them are there :/

**Comment by koenrh** [comment]
@viktae That is odd. I don't run Windows myself, but I'll see if I can reproduce it in a Windows VM. Thanks for reporting!

**Comment by FejkImer** [comment]
Hi, 
I encountered same issue, I used only windows, then Ubuntu on windows and got 215 error.
I got advice to hardcode your code and to remove os.env part and to directly enter my tokens and keys, but sadly I am not experienced that much yet, so would love if @viktae shared it with us. 

If you need more feedback concerning this issue, I am here to send you data if you need them, because you don't use Windows.

**Comment by koenrh** [comment]
@FejkImer That likely means that the script could somehow not read the environment variables.

After you have set the keys and tokens (per [these instructions](https://github.com/koenrh/delete-tweets#configure-your-environment)), could you check whether the variables are actually set?

Running this command should output the four Twitter environment variables: `env | grep TWITTER`

**Comment by FejkImer** [comment]
Here it is, I am using Ubuntu on Windows in this case

https://i.imgur.com/fJZhPSP.png

**Comment by koenrh** [comment]
@FejkImer Apologies for the delay. You should not include the brackets `[` `]` here:

```batchfile
set TWITTER_CONSUMER_KEY=[your consumer key]
set TWITTER_CONSUMER_SECRET=[your consumer secret]
set TWITTER_ACCESS_TOKEN=[your access token]
set TWITTER_ACCESS_TOKEN_SECRET=[your access token secret]
```

It is safer to just quote these values:

```batchfile
set TWITTER_CONSUMER_KEY="YOUR_CONSUMER_KEY"
set TWITTER_CONSUMER_SECRET="YOUR_CONSUMER_SECRET"
set TWITTER_ACCESS_TOKEN="YOUR_ACCESS_TOKEN"
set TWITTER_ACCESS_TOKEN_SECRET="YOUR_ACCESS_TOKEN_SECRET"
```

I'll make sure to clarify that in the README.
