### ISSUE TITLE
Bad Auth Data

### ISSUE THREAD

**Issue by pwadeveloper** [koenrh/delete-tweets#28]
Hello, thanks for this.
I keep getting this error

delete tweet 946339619297202176
Exception: [{'code': 215, 'message': 'Bad Authentication data.'}]

**Comment by MarkelFe** [comment]
You probably have entered the API keys wrong. Revise that you haven't entered extra spaces ^^

**Comment by koenrh** [comment]
Apologies for the delay.

As @MarkelFe says, please double check the credentials. And have a look at this section in the README: https://github.com/koenrh/delete-tweets#configure-your-environment.

Let me know if this doesn't solve the issue.
