### ISSUE TITLE
Key Error 

### ISSUE THREAD

**Issue by shaneswoll** [koenrh/delete-tweets#29]
Not sure why I'm getting this. The keys are correct, i even regenerated them and still get this message.  
<img width="560" alt="screen shot 2019-01-15 at 2 08 32 am" src="https://user-images.githubusercontent.com/23007169/51164401-cb6c8e80-186a-11e9-8c88-6fd94db0e98d.png">

**Comment by koenrh** [comment]
Apologies for the delay. 

Thanks, @GrantSheehan. Also see this section in the README: https://github.com/koenrh/delete-tweets#configure-your-environment

@shaneswoll Let me know if this does not solve the issue you are facing.
