### ISSUE TITLE
Twitter rate limits

### ISSUE THREAD

**Issue by micaswyers** [koenrh/delete-tweets#38]
Hello! 
Everything I see in the current Twitter documentation indicates a rate limit of 300 requests/3 hours (per application): https://blog.twitter.com/developer/en_us/topics/tools/2018/new-developer-requirements-to-protect-our-platform.html

"- Tweets & Retweets (combined): 300 per 3 hours"
I noticed that there's a comment about a "poor man's solution" to rate-limiting with a `time.sleep(.5)`. Has the rate limit been changed since then, or is deleting a special case?

Thank you very much!

**Comment by koenrh** [comment]
Hi! Good question. I am not sure. The limit for "destroy" requests used to be 450 per window, but I do not recall what the length of that window was. Unfortunately, rate limit information (x-rate-limit-limit, x-rate-limit-remaining, x-rate-limit-reset) is not included in responses to POST requests (e.g. `POST statuses/destroy/:id`).
