### ISSUE TITLE
Twitter API credentials not set 

### ISSUE THREAD

**Issue by iamselasie** [koenrh/delete-tweets#43]
OK, so I followed the steps to delete the tweets on my TimeLine. However, upon running the delete tweet python script on my CMD console, I get an error; Twitter API credentials not set. I do believe I exported all my credentials, however, I may have missed a couple of steps? I am not sure. Also, I figured the script might be outdated, following [@icommitfelonies](https://gist.github.com/icommitfelonies/) [butchered tweets code ](https://gist.github.com/icommitfelonies/6c793aa1c774dc84387167b5fba73e19).

The fact is that; I have the tweet.js file, which is about 100MB and I have the twitter app credentials created, but I believe your script advised us to use a certain CSV file, which I doubt works after 2018. 

Please, is there a new code? Are there guidelines to follow to help me use this new code? Please help. Thanks

**Comment by koenrh** [comment]
> OK, so I followed the steps to delete the tweets on my TimeLine. However, upon running the delete tweet python script on my CMD console, I get an error; Twitter API credentials not set. I do believe I exported all my credentials, however, I may have missed a couple of steps? I am not sure. Also, I figured the script might be outdated, following [@icommitfelonies](https://gist.github.com/icommitfelonies/) [butchered tweets code ](https://gist.github.com/icommitfelonies/6c793aa1c774dc84387167b5fba73e19).
> 
> The fact is that; I have the tweet.js file, which is about 100MB and I have the twitter app credentials created, but I believe your script advised us to use a certain CSV file, which I doubt works after 2018.

Twitter no longer supports CSV files, indeed. That was addressed in https://github.com/koenrh/delete-tweets/pull/36. 

The error simply means that the Python script could not find all of the following environment variables. Make sure that you have exported them as follows:

```bash
export TWITTER_CONSUMER_KEY="your_consumer_key"
export TWITTER_CONSUMER_SECRET="your_consumer_secret"
export TWITTER_ACCESS_TOKEN="your_access_token"
export TWITTER_ACCESS_TOKEN_SECRET="your_access_token_secret"
```

You can verify this by running `env | grep TWITTER`:

```bash
$ env | grep TWITTER

TWITTER_CONSUMER_KEY="your_consumer_key"
TWITTER_CONSUMER_SECRET="your_consumer_secret"
TWITTER_ACCESS_TOKEN="your_access_token"
TWITTER_ACCESS_TOKEN_SECRET="your_access_token_secret"
```
