### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by colemickens** [koenrh/delete-tweets#49]
```
# python deletetweets.py -d 2019-09-14 ../TWITTER2/tweet.js 
Traceback (most recent call last):
  File "deletetweets.py", line 112, in <module>
    main()
  File "deletetweets.py", line 108, in main
    delete(args.file, args.date, args.restrict, args.spare_ids, args.min_likes, args.min_retweets)
  File "deletetweets.py", line 77, in delete
    for row in TweetReader(tweets, date, r, s, min_l, min_r).read():
  File "deletetweets.py", line 59, in read
    if (self.min_likes > 0 and int(row.get("favorite_count")) >= self.min_likes) or \
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by lorainekv** [comment]
Noticed this same error - looks like min_l and min_r are coming in as `None` if they are not provided as command line arguments. Passing `None` into this function overrides the default int values set in the TweetReader constructor. 

I've got a working branch reproducing this error in a unit test, will send a fix by in a PR shortly.

**Comment by colemickens** [comment]
Thanks! Passing the CLI args worked in the meantime.

**Comment by koenrh** [comment]
Thanks for reporting. 

>I've got a working branch reproducing this error in a unit test, will send a fix by in a PR shortly.

🙌
