### ISSUE TITLE
Possibly incorrect test assertions for min_likes and min_retweets

### ISSUE THREAD

**Issue by lorainekv** [koenrh/delete-tweets#50]
Hi there! I was working on a PR to address [Issue 49](https://github.com/koenrh/delete-tweets/issues/49). 

However, I noticed some confusing discrepancies between the README and the test assertions, and wanted to clarify first before submitting PRs. 

**min_likes expectations:** 
https://github.com/koenrh/delete-tweets/blob/d4d9161addc25e953abef39507e522f912d370fa/test_deletetweets.py#L86
Shouldn't the expected value be `[{"id_str": "21"}]` ?

According to the [docs](https://github.com/koenrh/delete-tweets/blob/master/README.md#spare-tweets), it seems like the TweetReader should exclude any tweets with _at least_ one or more retweet.

If you take a look at the actual TweetReader list in that test case by dropping in a breakpoint.
```
actual = list(TweetReader(FakeReader(tweets), min_likes=1).read())
(Pdb) actual
=> [{'id_str': '21', 'favorite_count': 0}]
```  
--- 

**min_retweets expectations:**
Should this line
https://github.com/koenrh/delete-tweets/blob/d4d9161addc25e953abef39507e522f912d370fa/test_deletetweets.py#L97
be `expected = [{'id_str': '21', 'retweet_count': 0}]`? 
Just like the above example, inspecting the actual list in the test returns: `=> [{'id_str': '21', 'retweet_count': 0}]`

**Comment by lorainekv** [comment]
Since the expected lists don't match the actual lists, both of those tests are false positives. Might want to add
```
self.assertEqual(len(expected), len(actual))
```
to avoid false positives.

**Comment by koenrh** [comment]
Hi @lorainekv,

Apologies for the delayed response.

I think you are right! Feel free to submit the pull request.
