### ISSUE TITLE
--dry-run doesn't

### ISSUE THREAD

**Issue by kivikakk** [koenrh/delete-tweets#67]
I haven't looked into why, but it's worth noting that `--dry-run` doesn't appear to actually dry run right now — the tweets are deleted.

**Comment by koenrh** [comment]
I'm sorry, my bad 😞

**Comment by koenrh** [comment]
Published a new version: `pip install -U delete-tweets`. Thank you!

**Comment by kivikakk** [comment]
Thank you! <3
