### ISSUE TITLE
ImportError: cannot import name deletetweets

### ISSUE THREAD

**Issue by carlosvega** [koenrh/delete-tweets#71]
whenever I try to execute delete-tweets it raises the following error:

```
Traceback (most recent call last):
  File "env/bin/delete-tweets", line 5, in <module>
    from deletetweets.__main__ import main
  File "/Users/carlos.vega/Documents/deletetweets/twitter-2019-12-08/env/lib/python2.7/site-packages/deletetweets/__main__.py", line 7, in <module>
    from deletetweets import deletetweets
ImportError: cannot import name deletetweets
```

Either from a virtualenv or system wide.

**Comment by sschoenith** [comment]
I was able to fix this by:
- navigating to deletetweets location pip install location (for me, /usr/local/lib/python2.7/dist-packages/deletetweets)
- open __main__.py
- comment out line 7
- add "import deletetweets" on line 8
- re run deletetweets

That being said, its probably not a proper fix... but it works.

**Comment by koenrh** [comment]
My apologies for the delay.

As Python 2 is reaching [end of life](https://www.python.org/dev/peps/pep-0373/) in just two days, could you try using Python 3? If you already have Python3 installed: uninstall the package, and then force the package to be installed using Python 3 `python3 -m pip delete-tweets`.

**Comment by Raiuc** [comment]
python3 -m pip install delete-tweets

**Comment by IHIutch** [comment]
@sschoenith 's answer worked for me as well

**Comment by koenrh** [comment]
Python 2 is end of life. Updated the README to reflect that Python 3 should be used.
