### ISSUE TITLE
Cannot find Tweet.js on a Mac

### ISSUE THREAD

**Issue by artofofiare** [koenrh/delete-tweets#74]
I keep getting this error when I try to run `delete-tweets --until 2019-01-01 tweet.js `
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/delete-tweets", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deletetweets/__main__.py", line 53, in main
    deletetweets.delete(args.file, args.until_date, filters, args.spare_ids, args.min_likes, args.min_retweets, args.dry_run)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deletetweets/deletetweets.py", line 61, in delete
    with io.open(tweetjs_path, mode="r", encoding="utf-8") as tweetjs_file:
FileNotFoundError: [Errno 2] No such file or directory: 'tweet.js'
```

I have the very current version of Python installed, and Pip installed under Python 3. I also have tweet.js in all(delete-tweets and deletetweets) folders.

**Comment by koenrh** [comment]
The location of the `tweet.js` file (whether relative or absolute) should not really matter. Have you tried running the command with the absolute path to your `tweet.js` file?

For example:

```
delete-tweets --until 2019-01-01 /Users/koen/Downloads/tweet.js
``

**Comment by artofofiare** [comment]
About to try that right now. Give me a moment to setup my Keys...

**Comment by artofofiare** [comment]
> The location of the `tweet.js` file (whether relative or absolute) should not really matter as long as the file exists at that location. Have you tried running the command with the absolute path to your `tweet.js` file?
> 
> For example:
> 
> ```
> delete-tweets --until 2019-01-01 /Users/koen/Downloads/tweet.js
> ```

Voila! that was the zing I needed. My pip and python 3 just didn't know where `tweet.js` was located, even though I had plastered it everywhere.

Process is currently running for 17k tweets.

**Comment by walter-grace** [comment]
> > The location of the `tweet.js` file (whether relative or absolute) should not really matter as long as the file exists at that location. Have you tried running the command with the absolute path to your `tweet.js` file?
> > For example:
> > ```
> > delete-tweets --until 2019-01-01 /Users/koen/Downloads/tweet.js
> > ```
> 
> Voila! that was the zing I needed. My pip and python 3 just didn't know where `tweet.js` was located, even though I had plastered it everywhere.
> 
> Process is currently running for 17k tweets.
What did you do to create your tweet.js? I am having this same issue and not sure how you figured it out. Greatly appreciate your help.

**Comment by artofofiare** [comment]
> > > The location of the `tweet.js` file (whether relative or absolute) should not really matter as long as the file exists at that location. Have you tried running the command with the absolute path to your `tweet.js` file?
> > > For example:
> > > ```
> > > delete-tweets --until 2019-01-01 /Users/koen/Downloads/tweet.js
> > > ```
> > 
> > 
> > Voila! that was the zing I needed. My pip and python 3 just didn't know where `tweet.js` was located, even though I had plastered it everywhere.
> > Process is currently running for 17k tweets.
> > What did you do to create your tweet.js? I am having this same issue and not sure how you figured it out. Greatly appreciate your help.

If what you asked is what you are searching for, then this article might help get that. 
https://medium.com/@oyeAbhishek/how-to-get-your-top-tweets-without-any-external-tool-40a4a8076122
