### ISSUE TITLE
KeyError: 'id_str'

### ISSUE THREAD

**Issue by lilyli** [koenrh/delete-tweets#76]
When I run `delete-tweets --until 2017-12-01 tweet.js`, I get the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/delete-tweets", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/deletetweets/__main__.py", line 53, in main
    deletetweets.delete(args.file, args.until_date, filters, args.spare_ids, args.min_likes, args.min_retweets, args.dry_run)
  File "/usr/local/lib/python3.7/site-packages/deletetweets/deletetweets.py", line 72, in delete
    destroyer.destroy(row["id_str"])
KeyError: 'id_str'`

Any idea how to fix this issue?

**Comment by visuphi** [comment]
I also have this issue!

**Comment by jclwilson** [comment]
Same

**Comment by d-lowl** [comment]
Can confirm

**Comment by d-lowl** [comment]
I think I got it working. There was a minor file structure change or something. Will make a pull request when confirm

**Comment by d-lowl** [comment]
Update: yeah, my idea was right, however there's already a pull request with the fix
#75

**Comment by koenrh** [comment]
Thanks for reporting! Should be fixed in the latest version: `pip install -U delete-tweets`.
