### ISSUE TITLE
Has anyone got suspended before?

### ISSUE THREAD

**Issue by teddy-dev** [koenrh/delete-tweets#81]
So i want to try this app. But I'm afraid my Twitter account will be suspended. There is no information about destroy tweet limit, it doesnt like post update tweet and get tweet. 

Has anyone got suspended before? Or has anyone try to delete more than tens of thousands of tweets in a short period of time?

**Comment by koenrh** [comment]
Hello @teddy-dev! No, not as far as I am aware. Twitter has implemented strict rate-limiting, which means that you could only delete tweets at a rate of N tweets per window. See related discussion: https://github.com/koenrh/delete-tweets/issues/38.

**Comment by anor4k** [comment]
reopening this because i did get suspended permanently for using this tool. I used it to delete 100k+ tweets, which took a few hours. I was unaware of the rate limit. proof: 
![Suspension](https://user-images.githubusercontent.com/19380886/95519753-2a0d6080-099c-11eb-943b-3bcd85dd4bbd.png)

**Comment by koenrh** [comment]
@anor4k I'm sorry to hear that 😞 This is the first time I have heard about someone actually getting suspended for using Twitter's API to delete their tweets. I don't think it has anything to do with Twitter's rate limit as this tool will simply [sleep](https://python-twitter.readthedocs.io/en/latest/rate_limits.html) for N seconds after it hits the rate limit. Which means it must have something to do with the large number of tweets being deleted.

From their [Developer Agreement and Policy](https://developer.twitter.com/en/developer-terms/agreement-and-policy):

>* Never perform bulk, aggressive, or spammy actions, including [bulk following](https://twittercommunity.com/t/policy-clarification-aggressive-following-and-inorganic-following-behavior/92769)

But then again there are a ton of (paid) services out there that do the same thing (even on accounts with a large number of tweets) without any issues.
