### ISSUE TITLE
One precision in directions

### ISSUE THREAD

**Issue by BorisAnthony** [koenrh/delete-tweets#85]
Hi!
"Unpack the archive, and move tweet.js to the same directory as this script."
This is not clear. What directory?
The directory where delete-tweets gets installed by Pip? (Which would be "/usr/local/bin/delete-tweets")
Or the directory we're running the script from (assuming the shell is always somehow "in" a directory")?
Or… what? Where? :)

Thanks for clarifying!

**Comment by koenrh** [comment]
Hello @BorisAnthony,

That needs updating. It doesn't matter where the `tweet.js` file is stored. It should read:

>Unpack the archive, and move tweet.js to **a** directory as this script.

If you have stored the file in `/Users/foo/tweet.json`, you can call the script with that location as argument:

`delete-tweets --until 2018-01-01 /Users/foo/tweet.js`

I'll update the README.
