### ISSUE TITLE
Update Build job to exclude deprecated Python 3.5

### ISSUE THREAD

**Issue by adrianteri** [koenrh/delete-tweets#96]
I noticed in the workflow job build for 3.5 there is a warning that 3.5 will be dropped in **January 2020** as seen below ...

![Screenshot from 2021-01-11 02-21-21](https://user-images.githubusercontent.com/10687877/104138286-2d0d5800-53b4-11eb-8bed-095e5298226a.png)

This is also evidenced elsewhere in the [docker library for python](https://github.com/docker-library/python/issues/556) with official docker images being purged containing this version https://github.com/docker-library/python/commit/93ddb24e33564a4f70f945a9fe603488bfd3a31e

**Comment by koenrh** [comment]
Thanks for reporting and fixing!
